### ISSUE TITLE
Make it not affect placements

### ISSUE THREAD

**Issue by flibber-hk** [dpinela/RainbowEggs#1]
I think it's fine if you prefer it to affect placements, this is more a suggestion than a request.

**Comment by dpinela** [comment]
I wouldn't mind making it not affect placements - in fact it would be convenient so that if, for example, a group of people are playing a seed together they can individually choose whether to use the mod or not. However I don't know how I would accomplish this. Maybe I could somehow replace the eggs *after* placements are done, instead of editing the pool before?

**Comment by flibber-hk** [comment]
Yeah, I think one way to do it would be to modify the `realItemCreator` of the rancid egg [item request](https://github.com/homothetyhk/RandomizerMod/blob/master/RandomizerMod/RC/Requests/ItemRequestInfo.cs#L13) to select a random rainbow egg AbstractItem? This way the spoiler log wouldn't inform which type of egg each location was (I guess you could write a rainbow eggs spoiler log if you really wanted). Alternatively, you could use the `onRandomizerFinish` event to replace a rancid egg with a coloured egg - this would mean other placements aren't affected, but the hash would be modified.

**Comment by dpinela** [comment]
I ended up using `realItemCreator`, but to put a tag on the egg items rather than replace them, and then do the actual replacement in `ModifyItem`. This not only keeps placements and hash the same, it will even work in ItemSync if not all players in a room are using this mod.

**Comment by dpinela** [comment]
This is now implemented in version 1.1.
